version: '3'
services:
  nfl-rushing-backend:
    container_name: nfl-rushing-backend
    build: backend/.
    ports:
      - "8081:8080"

  nfl-rushing-frontend:
    container_name: nfl-rushing-frontend
    build: frontend/nfl-rushing/.
    ports:
      - "8080:80"
    depends_on:
      - nfl-rushing-backend
    links:
      - nfl-rushing-backend


